"""Add overall meeting metrics to efficiency analysis

Revision ID: 8be6cda599ae
Revises: b15f90cfcefa
Create Date: 2025-11-27 08:35:51.237514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8be6cda599ae'
down_revision: Union[str, None] = 'b15f90cfcefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meeting_efficiency_analysis_audio_file_id', table_name='meeting_efficiency_analysis')
    op.drop_index('ix_meeting_efficiency_analysis_id', table_name='meeting_efficiency_analysis')
    op.drop_table('meeting_efficiency_analysis')
    op.drop_index('ix_user_confirmations_audio_file_id', table_name='user_confirmations')
    op.drop_index('ix_user_confirmations_id', table_name='user_confirmations')
    op.drop_table('user_confirmations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_confirmations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('audio_file_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_speaker_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_names', mysql.JSON(), nullable=False),
    sa.Column('confirmed_nicknames', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], name='user_confirmations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_confirmations_id', 'user_confirmations', ['id'], unique=False)
    op.create_index('ix_user_confirmations_audio_file_id', 'user_confirmations', ['audio_file_id'], unique=False)
    op.create_table('meeting_efficiency_analysis',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('audio_file_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entropy_values', mysql.JSON(), nullable=True),
    sa.Column('entropy_avg', mysql.FLOAT(), nullable=True),
    sa.Column('entropy_std', mysql.FLOAT(), nullable=True),
    sa.Column('speaker_metrics', mysql.JSON(), nullable=False),
    sa.Column('total_speakers', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_turns', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_sentences', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analysis_version', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('analyzed_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], name='meeting_efficiency_analysis_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_meeting_efficiency_analysis_id', 'meeting_efficiency_analysis', ['id'], unique=False)
    op.create_index('ix_meeting_efficiency_analysis_audio_file_id', 'meeting_efficiency_analysis', ['audio_file_id'], unique=False)
    # ### end Alembic commands ###
